apiVersion: apps/v1
kind: Deployment
metadata:
  name: freefacts-deployment
  namespace: default
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: freefacts-deployment
  template:
    metadata:
      labels:
        app: freefacts-deployment
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - freefacts-deployment
                topologyKey: kubernetes.io/hostname
      containers:
        - name: freefacts-deployment
          image: amitgujar/freefacts:_latest_
          ports:
            - containerPort: 3000
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: freefacts-config
                  key: mongodb-host
            - name: MONGODB_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: freefacts-config
                  key: mongodb-options
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: freefacts-secrets
                  key: username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: freefacts-secrets
                  key: password